package team44.project2.service.employee;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.jboss.logging.Logger;

import team44.project2.model.Employee;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Service class responsible for CRUD operations on employee records, providing methods
 * to retrieve all employees, add new employees, update existing ones, and delete them.
 */
@ApplicationScoped
public class EmployeeService {

    private static final Logger LOG = Logger.getLogger(EmployeeService.class);

    @Inject
    DataSource dataSource;
    //sql queries for employee operations
    private static final String GET_ALL_EMPLOYEES = """
        SELECT employee_id,
               first_name,
               last_name,
               role,
               start_date,
               email,
               password_hash,
               is_active
        FROM employees
        ORDER BY last_name, first_name
        """;

    private static final String INSERT_EMPLOYEE = """
        INSERT INTO employees
        (first_name, last_name, role, start_date, email, password_hash, is_active)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """;

    private static final String UPDATE_EMPLOYEE = """
        UPDATE employees
        SET first_name = ?,
            last_name = ?,
            role = ?,
            start_date = ?,
            email = ?,
            password_hash = ?,
            is_active = ?
        WHERE employee_id = ?
        """;

    private static final String DELETE_EMPLOYEE = """
        DELETE FROM employees
        WHERE employee_id = ?
        """;

    /**
     * Fetches all employees from the database, ordered by last name then first name.
     *
     * @return A list of all {@link team44.project2.model.Employee} records; empty if
     *         none exist or a database error occurs.
     */
    public List<Employee> getAllEmployees() {

        List<Employee> employees = new ArrayList<>();

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(GET_ALL_EMPLOYEES);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                employees.add(mapEmployee(rs));
            }

        } catch (SQLException e) {
            LOG.error("Error fetching employees", e);
        }

        return employees;
    }

    /**
     * Inserts a new employee record into the database using the data in the provided
     * {@link team44.project2.model.Employee}.
     *
     * @param employee The employee to insert (ID field is ignored; generated by the DB).
     */
    public void addEmployee(Employee employee) {

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(INSERT_EMPLOYEE)) {

            ps.setString(1, employee.firstName());
            ps.setString(2, employee.lastName());
            ps.setString(3, employee.role());
            ps.setDate(4, Date.valueOf(employee.startDate()));
            ps.setString(5, employee.email());
            ps.setString(6, employee.passwordHash());
            ps.setBoolean(7, employee.isActive());

            ps.executeUpdate();

        } catch (SQLException e) {
            LOG.error("Error inserting employee", e);
        }
    }

    /**
     * Updates an existing employee record by matching on the employee ID.
     *
     * @param employee The employee whose data should be persisted; must have a valid
     *                 {@code employeeId}.
     */
    public void updateEmployee(Employee employee) {

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(UPDATE_EMPLOYEE)) {

            ps.setString(1, employee.firstName());
            ps.setString(2, employee.lastName());
            ps.setString(3, employee.role());
            ps.setDate(4, Date.valueOf(employee.startDate()));
            ps.setString(5, employee.email());
            ps.setString(6, employee.passwordHash());
            ps.setBoolean(7, employee.isActive());
            ps.setInt(8, employee.employeeId());

            ps.executeUpdate();

        } catch (SQLException e) {
            LOG.error("Error updating employee", e);
        }
    }

    /**
     * Deletes the employee with the given ID from the database.
     *
     * @param employeeId The primary key of the employee to delete.
     */
    public void deleteEmployee(int employeeId) {

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(DELETE_EMPLOYEE)) {

            ps.setInt(1, employeeId);
            ps.executeUpdate();

        } catch (SQLException e) {
            LOG.error("Error deleting employee", e);
        }
    }

    /**
     * Maps the current row of the given {@link java.sql.ResultSet} to an
     * {@link team44.project2.model.Employee} instance.
     *
     * @param rs An open {@code ResultSet} positioned at the row to map.
     * @return The constructed {@code Employee}.
     * @throws java.sql.SQLException If any column access fails.
     */
    private Employee mapEmployee(ResultSet rs) throws SQLException {
        java.sql.Date sqlDate = rs.getDate("start_date");
        java.time.LocalDate startDate = (sqlDate != null) ? sqlDate.toLocalDate() : null;

        return new Employee(
                rs.getInt("employee_id"),
                rs.getString("first_name"),
                rs.getString("last_name"),
                rs.getString("role"),
                startDate,
                rs.getString("email"),
                rs.getString("password_hash"),
                rs.getBoolean("is_active")
        );
    }
}