package team44.project2.model.report;

import java.math.BigDecimal;
import java.time.LocalDate;
/**
 * Immutable record representing the aggregated sales data for a single product on a
 * given date, capturing the quantity sold and total revenue generated.
 *
 * @param saleDate    The calendar date on which the sales occurred.
 * @param productName The display name of the product.
 * @param quantity    The total number of units of this product sold on this date.
 * @param totalPrice  The total revenue generated by this product on this date.
 */
public record ProductSalesData(
        LocalDate saleDate,
        String productName,
        Integer quantity,
        BigDecimal totalPrice
) {
}
