package team44.project2.service.inventory;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import javax.sql.DataSource;

import team44.project2.model.Inventory;
import io.quarkus.logging.Log;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Service class responsible for CRUD operations on inventory items, including fetching
 * current stock levels, updating quantities, adding new items, and deleting items that
 * are no longer carried.
 */
@ApplicationScoped
public class InventoryService {

    @Inject
    DataSource dataSource;
    //sql queries for inventory operations
    private static final String GET_ALL_INVENTORY = """
        SELECT inventory_id,
               item_name,
               category,
               current_quantity,
               unit,
               reorder_threshold,
               supplier_cost,
               last_restock_date
        FROM inventory
        ORDER BY item_name
        """;

    private static final String UPDATE_STOCK = """
        UPDATE inventory
        SET current_quantity = ?,
            last_restock_date = CURRENT_DATE
        WHERE inventory_id = ?
        """;

    private static final String INSERT_INVENTORY = """
        INSERT INTO inventory (item_name, category, current_quantity, unit, reorder_threshold, supplier_cost, last_restock_date)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """;

    private static final String DELETE_INVENTORY = """
        DELETE FROM inventory
        WHERE inventory_id = ?
        """;

    /**
     * Fetches all inventory items from the database, ordered alphabetically by item name.
     *
     * @return A list of all {@link team44.project2.model.Inventory} records; empty if
     *         none exist or a database error occurs.
     */
    public List<Inventory> getAllInventory() {

        List<Inventory> inventoryList = new ArrayList<>();

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(GET_ALL_INVENTORY);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                inventoryList.add(mapInventory(rs));
            }

        } catch (SQLException e) {
            Log.error("Error fetching inventory", e);
        }

        return inventoryList;
    }

    /**
     * Sets the current stock quantity of the specified inventory item and updates the
     * {@code last_restock_date} to today.
     *
     * @param inventoryId The primary key of the item to update.
     * @param newQuantity The new stock quantity to persist.
     */
    public void updateStock(int inventoryId, java.math.BigDecimal newQuantity) {

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(UPDATE_STOCK)) {

            ps.setBigDecimal(1, newQuantity);
            ps.setInt(2, inventoryId);

            ps.executeUpdate();

        } catch (SQLException e) {
            Log.error("Error updating inventory stock", e);
        }
    }

    /**
     * Inserts a new inventory item into the database.
     *
     * @param item The {@link team44.project2.model.Inventory} record to insert; the
     *             {@code inventoryId} field is ignored and generated by the database.
     */
    public void addInventoryItem(team44.project2.model.Inventory item) {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(INSERT_INVENTORY)) {

            ps.setString(1, item.itemName());
            ps.setString(2, item.category());
            ps.setBigDecimal(3, item.currentQuantity() != null ? item.currentQuantity() : java.math.BigDecimal.ZERO);
            ps.setString(4, item.unit());
            ps.setBigDecimal(5, item.reorderThreshold() != null ? item.reorderThreshold() : java.math.BigDecimal.ZERO);
            ps.setBigDecimal(6, item.supplierCost() != null ? item.supplierCost() : java.math.BigDecimal.ZERO);

            if (item.lastRestockDate() != null) {
                ps.setDate(7, java.sql.Date.valueOf(item.lastRestockDate()));
            } else {
                ps.setDate(7, null);
            }

            ps.executeUpdate();

        } catch (SQLException e) {
            Log.error("Error adding inventory item", e);
        }
    }

    /**
     * Permanently deletes the inventory item identified by the given ID.
     *
     * @param inventoryId The primary key of the item to remove.
     */
    public void deleteInventoryItem(int inventoryId) {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(DELETE_INVENTORY)) {

            ps.setInt(1, inventoryId);
            ps.executeUpdate();

        } catch (SQLException e) {
            Log.error("Error deleting inventory item", e);
        }
    }

    /**
     * Maps the current row of the given {@link java.sql.ResultSet} to an
     * {@link team44.project2.model.Inventory} instance.
     *
     * @param rs An open {@code ResultSet} positioned at the row to map.
     * @return The constructed {@code Inventory} record.
     * @throws java.sql.SQLException If any column access fails.
     */
    private Inventory mapInventory(ResultSet rs) throws SQLException {

        java.sql.Date sqlDate = rs.getDate("last_restock_date");
        java.time.LocalDate lastRestockDate = (sqlDate != null) ? sqlDate.toLocalDate() : null;

        return new Inventory(
                rs.getInt("inventory_id"),
                rs.getString("item_name"),
                rs.getString("category"),
                rs.getBigDecimal("current_quantity"),
                rs.getString("unit"),
                rs.getBigDecimal("reorder_threshold"),
                rs.getBigDecimal("supplier_cost"),
                lastRestockDate
        );
    }
}
